Kmerald: a new method for allele detection based on k-mer alignment by Hufsah Ashraf.
whatshap/whatshap pull request #481
Opened 2023-09-10 06:47 UTC by tobiasmarschall

2023-09-10 06:51 UTC, tobiasmarschall commented
@Hufsah-Ashraf Thanks a lot for all your work on this! Could you take a look whether you are happy with how I squashed commits and edited the commit messages? (I left the old branch for now, we should delete once merged).
@marcelm I want to merge this tomorrow. Please let me know in case you have objections (or want time to look at the code).

2023-09-10 06:54 UTC, tobiasmarschall commented
@Hufsah-Ashraf Did you write test cases for this as well? If yes it appears you haven't pushed them...

2023-09-11 11:29 UTC, marcelm requested changes
Hi, thanks for this. I have a couple of comments and it would be nice if at least some of them were addressed before this is merged. If this needs to be merged tomorrow, then this would be the minimum:
- Remove `kmerald_doc.txt`
- Change spelling of command-line options
- Fix ReST issues in the documentation
- Add a changelog entry

Also, since there are no tests, this is going to be difficult to maintain.

The `realign()` method is getting too big and needs to be refactored so that the kmerald and non-kmerald code is nicely separate. I will probably need to help with that.

2023-09-11 11:29 UTC, marcelm commented on whatshap/align.pyx
> +		c = reference[i]
```suggestion
	for i, c in enumerate(reference):
```

2023-09-11 11:29 UTC, marcelm commented on whatshap/phred_scores.py
> +        counts_file = open(file, "r")
Please use a context manager: `with open(file):` (to close the file automatically when no longer needed). See [the example in the csv.reader documentation](https://docs.python.org/3/library/csv.html#csv.reader).

2023-09-11 11:29 UTC, marcelm commented on whatshap/phred_scores.py
> +                probs[new_key] = count
You can avoid the "check if key is in dict and then update, else set" pattern by using a [defaultdict](https://docs.python.org/3/library/collections.html#collections.defaultdict).

Initialize probs thus:
```
probs = defaultdict(int)
```
then update:
```
probs[new_key] += count
```

(Same for `seen_comb`)

2023-09-11 11:29 UTC, marcelm commented on whatshap/phred_scores.py
> +    writer = open(outputfile, "w")
Use a context manager here as well (`with open(outputfile, "w")` as writer:`)

2023-09-11 11:29 UTC, marcelm commented on whatshap/phred_scores.py
> +            writer.write(str(s[0]) + "\t" + str(s[1]) + "\t" + str(phred_score) + "\n")
`print()` is much nicer here:
```suggestion
            print(s[0], s[1], phred_score, sep="\t", file=writer)
```
(Same below.)

2023-09-11 11:29 UTC, marcelm commented on whatshap/variants.py
> +            self._kmerald_costs = False
These "unused" attributes should be set to `None`.

2023-09-11 11:29 UTC, marcelm commented on whatshap/variants.py
> +        if use_kmerald:
This is getting too hard to read and maintain and needs to be refactored.

2023-09-11 11:29 UTC, marcelm commented on whatshap/variants.py
> +                reader = csv.reader(costs_file, delimiter="\t")
Reading the CSV should not be done in the constructor of `ReadSetReader`.

2023-09-11 19:07 UTC, tobiasmarschall commented
Thanks @marcelm. The reason why I wanted to merge fast is because we want to submit a revision of a paper describing this method. But thinking about this, we should maybe decouple the two and add test cases before merging. Marcel, if you want to do more review, we would also wait before merging.

2023-09-12 06:34 UTC, marcelm commented
If there were tests, I would be ok with merging this as-is because I could just fix the remaining issues later if necessary. But as it stands, I don’t even know whether this works.

If you think the paper would benefit if kmerald is available in `main`, then you could merge now and add the tests within the next couple of days; that would be fine with me. I would also be happy to help with refactoring that I requested.

2023-09-12 20:36 UTC, Hufsah-Ashraf commented
Thanks @tobiasmarschall and @marcelm. I have tried to address them. Please let me know if you still see any issues or want any changes/additions. I agree with Tobias about holding back on the merge till the test cases are added. I will try to add the them as soon as possible.

2023-09-12 20:58 UTC, marcelm approved these changes

2023-09-18 12:45 UTC, tobiasmarschall commented
@Hufsah-Ashraf Thanks! Just one last request: Could you remove `tests/data/short-genome/learn-data/observed.txt` and have the test case generate a file in a temporary place? See for example this test for how that's done: 
https://github.com/whatshap/whatshap/blob/c7ece953dccf101cbd0f99471b122ea2188dac05/tests/test_run_haplotag.py#L10
On that note, could you rename `learn()` method in` whatshap/cli/learn.py to `run_learn()` for consistency? Also `test_learn.py` should be `test_run_learn.py`, which we are using for the integration tests of the whole run functions.

2023-09-18 14:39 UTC, merged